name: dotnet5-selenium-slack-dockerhub-azureappservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/siteconversordistancias-dotnet5
  CAMINHO_PROJETO_TESTES: ./ConversorDistancias.Testes
  NOME_WEBAPP: groffe-conversordistancias

jobs:
  build-docker-tests-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build de imagem
      run: |
        cd ./ConversorDistancias
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest
    - name: Criação de container para testes com o site
      run: |
        docker run --name site-testes -p 1234:80 -d ${{ env.IMAGEM_DOCKERHUB }}:latest
        docker container ls
        
    - name: Testes com Selenium WebDriver + Chrome Driver
      env:
        UrlTelaConversaoDistancias: http://localhost:1234
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal
      
    - name: Login no Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Geração de tag com número do Build e Push no Docker Hub
      run: |
        docker tag ${{ env.IMAGEM_DOCKERHUB }}:latest ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.IMAGEM_DOCKERHUB }}

    - name: Notificação de sucesso na execução
      if: success()
      shell: pwsh
      run: |
        $Execucao = '{ "workflow": "' + ${env:GITHUB_WORKFLOW} + '", "numExecucao": ' + ${env:GITHUB_RUN_NUMBER} + ' }'
        Write-Host $Execucao
        Invoke-RestMethod -Uri "${{ secrets.URL_LOGIC_APP_SUCESSO }}" -Method POST -ContentType "application/json" -Body $Execucao
    
    - name: Notificação de erro na execução
      if: failure()
      shell: pwsh
      run: |
        $Execucao = '{ "workflow": "' + ${env:GITHUB_WORKFLOW} + '", "numExecucao": ' + ${env:GITHUB_RUN_NUMBER} + ' }'
        Write-Host $Execucao
        Invoke-RestMethod -Uri "${{ secrets.URL_LOGIC_APP_FALHA }}" -Method POST -ContentType "application/json" -Body $Execucao
        
  deployment-azwebapp:
    needs: [build-docker-tests-push]

    runs-on: ubuntu-latest

    steps:
    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp - Deployment da Aplicacao
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: '${{ env.IMAGEM_DOCKERHUB }}:${{ github.run_number }}'